INSERT INTO subjects (subject) VALUES ('anatomy');
INSERT INTO subjects (subject) VALUES ('biology');
INSERT INTO subjects (subject) VALUES ('chemistry');
INSERT INTO subjects (subject) VALUES ('accountancy');
INSERT INTO subjects (subject) VALUES ('economy');
INSERT INTO subjects (subject) VALUES ('physics');
INSERT INTO subjects (subject) VALUES ('informatics');
INSERT INTO subjects (subject) VALUES ('logic');
INSERT INTO subjects (subject) VALUES ('math');
INSERT INTO subjects (subject) VALUES ('civic culture');
INSERT INTO subjects (subject) VALUES ('philosophy');
INSERT INTO subjects (subject) VALUES ('geography');
INSERT INTO subjects (subject) VALUES ('history');
INSERT INTO subjects (subject) VALUES ('psychology');
INSERT INTO subjects (subject) VALUES ('sociology');
INSERT INTO subjects (subject) VALUES ('latin');
INSERT INTO subjects (subject) VALUES ('hungarian');
INSERT INTO subjects (subject) VALUES ('romanian');
INSERT INTO subjects (subject) VALUES ('arabic');
INSERT INTO subjects (subject) VALUES ('chinese');
INSERT INTO subjects (subject) VALUES ('korean');
INSERT INTO subjects (subject) VALUES ('hebrew');
INSERT INTO subjects (subject) VALUES ('english');
INSERT INTO subjects (subject) VALUES ('finnish');
INSERT INTO subjects (subject) VALUES ('french');
INSERT INTO subjects (subject) VALUES ('german');
INSERT INTO subjects (subject) VALUES ('greek');
INSERT INTO subjects (subject) VALUES ('italian');
INSERT INTO subjects (subject) VALUES ('japanese');
INSERT INTO subjects (subject) VALUES ('hungarian');
INSERT INTO subjects (subject) VALUES ('norwegian');
INSERT INTO subjects (subject) VALUES ('dutch');
INSERT INTO subjects (subject) VALUES ('portuguese');
INSERT INTO subjects (subject) VALUES ('russian');
INSERT INTO subjects (subject) VALUES ('spanish');
INSERT INTO subjects (subject) VALUES ('sweedish');
INSERT INTO subjects (subject) VALUES ('turkish');
INSERT INTO subjects (subject) VALUES ('architecture');
INSERT INTO subjects (subject) VALUES ('drawing');
INSERT INTO subjects (subject) VALUES ('artistic education');
INSERT INTO subjects (subject) VALUES ('art education');
INSERT INTO subjects (subject) VALUES ('photo');
INSERT INTO subjects (subject) VALUES ('history of the arts');
INSERT INTO subjects (subject) VALUES ('sculpture');
INSERT INTO subjects (subject) VALUES ('theater and film');
INSERT INTO subjects (subject) VALUES ('music education');
INSERT INTO subjects (subject) VALUES ('sports');
INSERT INTO subjects (subject) VALUES ('law');
INSERT INTO subjects (subject) VALUES ('technology');


