INSERT INTO grades (grade) VALUES ('0');
INSERT INTO grades (grade) VALUES ('01');
INSERT INTO grades (grade) VALUES ('02');
INSERT INTO grades (grade) VALUES ('03');
INSERT INTO grades (grade) VALUES ('04');
INSERT INTO grades (grade) VALUES ('05');
INSERT INTO grades (grade) VALUES ('06');
INSERT INTO grades (grade) VALUES ('07');
INSERT INTO grades (grade) VALUES ('08');
INSERT INTO grades (grade) VALUES ('09');
INSERT INTO grades (grade) VALUES ('10');
INSERT INTO grades (grade) VALUES ('11');
INSERT INTO grades (grade) VALUES ('12');
INSERT INTO grades (grade) VALUES ('1st year student');
INSERT INTO grades (grade) VALUES ('2nd year student');
INSERT INTO grades (grade) VALUES ('3rd year student');
INSERT INTO grades (grade) VALUES ('4th year student');
INSERT INTO grades (grade) VALUES ('5th year student');
INSERT INTO grades (grade) VALUES ('6th year student');
INSERT INTO grades (grade) VALUES ('masterand student');
INSERT INTO grades (grade) VALUES ('doctorand student');